<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.editorconfig</string>
	</array>
	<key>name</key>
	<string>EditorConfig</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.ini</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ini.editorconfig</string>
	<key>uuid</key>
	<string>9175a436-a65b-11e3-be40-425861b86ab6</string>
</dict>
</plist>
